server:
  port: 20003
spring:
  application:
    name: @artifactId@
  #数据源配置
  datasource:
    url: ${zshy.datasource.url}
    username: ${zshy.datasource.username}
    password: ${zshy.datasource.password}
