#Swagger属性配置
mate:
  swagger:
    enable: false
    title: ZshyCloud文档管理中心
    description: ZshyCloud文档管理
    license: Powered by ZshyCloud
    contact-name: yanghaifeng
    contact-email: 694939483@qq.com
# knife4j配置
knife4j:
  enable: ${zshy.swagger.enable}
  # 开启生产环境屏蔽
  production: false
  basic:
    enable: true
    username: admin
    password: zshycloud
  setting:
    # 是否不显示Knife4j默认的footer，默认为true(显示)
    enableFooter: false
    # 是否自定义Footer，默认为false(非自定义)
    enableFooterCustom: true
    # 自定义Footer内容,支持Markdown语法
    footerCustomContent: Apache License 2.0 | Copyright  2020-[北京中数合一科技有限公司]